version: '3.8'

services:
  js-backend:
    build:
      context: ./backend
    container_name: js-backend
    restart: unless-stopped
    init: true
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    environment:
      - DRIZZLE_DATABASE_URL=mysql://root:root@db:3306/db
    depends_on:
      - db
    networks:
      - natural-language-date-interpreter_app-network

  ts-frontend:
    build:
      context: ./frontend
    container_name: ts-frontend
    restart: unless-stopped
    init: true
    ports:
      - "4200:4200"
    networks:
      - natural-language-date-interpreter_app-network

  db:
    image: mysql:latest
    container_name: drizzle-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - natural-language-date-interpreter_app-network

volumes:
  db-data:

networks:
  natural-language-date-interpreter_app-network:
    driver: bridge